### ISSUE TITLE
Wrong memory value in tooltips

### ISSUE THREAD

**Issue by pojar** [udda/multiload-ng#10]
When you hover the mouse over the indicator value of the memory is not correctly displayed. I see 0% or 100% value only.
On Xubuntu 16.04.1 (XFCE 4.12)
![image](https://cloud.githubusercontent.com/assets/5154768/18056324/18fb2fac-6e14-11e6-9931-e2fff934b262.gif)

**Comment by udda** [comment]
Hello, thanks for the report. Does the *detailed* tooltip show the correct value?

You can change tooltip style using the button next to graph size.

**Comment by pojar** [comment]
![- _2016-08-29_18-55-14](https://cloud.githubusercontent.com/assets/5154768/18057807/2c12c8ba-6e1a-11e6-9831-ff0cc36bc3e9.png)

**Comment by pojar** [comment]
63+93 = 156% RAM i have :)

**Comment by pojar** [comment]
After reboot:
![- _2016-08-29_19-48-33](https://cloud.githubusercontent.com/assets/5154768/18059515/f15e7b8a-6e21-11e6-8ca8-dc5750bdbb21.png)

**Comment by udda** [comment]
User and cache memory counts both include shared memory, so it's perfectly reasonable that the sum of them is over 100% under some workloads. I will fix soon this counter-intuitive behavior (making they sum up 100%), but technically this is not a bug.

About the issue, I made a commit that should fix the percent display, let me know if this solves the problem.
If it does not work yet, please post results of `cat /proc/meminfo` (along with a new screenshot like the last one).

**Comment by haarp** [comment]
Yes, something is seriously borked through and through, and has been since the nandhp version.

Right now it's claiming that 50% is in use by programs (reality: closer to 23%) and 100% in use by cache (cannot possibly add up!)

Also when I store a large file on tmpfs, the graph shows both User and Shared increasing, neither of which is in any way correct (and programs like htop do not show this effect)

**Comment by udda** [comment]
I'm planning to drop libgtop dependency, and read directly sysfs nodes, like *top*, *free* and similar tools do. 

I already had to work around another libgtop bug about disk speed reporting. This is getting messy to fix and maintain, so maybe it's better to just do it myself.
