### ISSUE TITLE
Custom graph order

### ISSUE THREAD

**Issue by haarp** [udda/multiload-ng#12]
Especially with the increasing number of graphs available, being able to reorder them would be very useful, I think.

**Comment by udda** [comment]
This requires a large code rework. It's a planned upgrade, but will require some time.

A workaround for the moment could be using multiple plugins arranged in desired order.

**Comment by udda** [comment]
Graph reordering support was added with commits [6e80329](https://github.com/udda/multiload-ng/commit/6e8032966d01f6ae4aa8a07fd7e9f39aa6cbc4d0) and  [df57557](https://github.com/udda/multiload-ng/commit/df575570bcf780eef1da67b3024c9a6837e55574).
