### ISSUE TITLE
Does not show up in xfce4-panel once added

### ISSUE THREAD

**Issue by haarp** [udda/multiload-ng#13]
I'm planning on switching from multiload-nandhp on one of my Xfce machines. The plugin compiles and installs just fine, the standalone application also works. However, adding the panel plugin to xfce4-panel-4.12.0 fails. The plugin is added but will not show up. Panel log after adding:

(wrapper-1.0:28110): multiload-ng-core-WARNING **: multiload_ui_read: settings = NULL
(wrapper-1.0:28110): GLib-GObject-WARNING **: cannot register existing type 'GtkWidget'
(wrapper-1.0:28110): GLib-GObject-WARNING **: cannot add class private field to invalid type '<invalid>'
(wrapper-1.0:28110): GLib-GObject-WARNING **: cannot add private field to invalid (non-instantiatable) type '<invalid>'
(wrapper-1.0:28110): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(wrapper-1.0:28110): GLib-GObject-WARNING **: cannot register existing type 'GtkBuildable'
(wrapper-1.0:28110): GLib-GObject-CRITICAL **: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
(wrapper-1.0:28110): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(wrapper-1.0:28110): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(wrapper-1.0:28110): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
(wrapper-1.0:28110): GLib-GObject-WARNING **: cannot add private field to invalid (non-instantiatable) type '<invalid>'

**Comment by udda** [comment]
Thanks for the report. Please give me additional details.
* Are you using lastest git code or 1.2.0 release? 
* Which distro are you using?
* Please post output of `uname - a`
* Every other thing you think it's relevant

**Comment by haarp** [comment]
I tested it with both 1.2.0 and git.

Linux hellbringer 4.7.2-gentoo-H #2 SMP Mon Aug 22 09:41:10 CEST 2016 x86_64 Intel(R) Core(TM) i7-3920XM CPU @ 2.90GHz GenuineIntel GNU/Linux

This is Gentoo Linux amd64, newest Xfce (xfce4-panel-4.12.0)

multiload-nandhp works fine in the panel, as does multiload-ng's standalone app.

**Comment by udda** [comment]
Which command line you used for ./configure? I suspect you selected GTK+3 build. You have to build with GTK+2 for XFCE panel.

**Comment by haarp** [comment]
That was it! xfce4-panel expects GTK2. Works now, Thanks! :)
