### ISSUE TITLE
Lubuntu Package

### ISSUE THREAD

**Issue by huseyinkozan** [udda/multiload-ng#2]
Hello,

Is it possible to package your software for Lubuntu 16.04 ? I tried to install with autogen, configure, make, make install but got some stuations. Here them:

Installed the required libraries : 
```
sudo apt-get install lxpanel-dev libgtop2-dev libgtk2.0-dev libglib2.0-dev libcairo2-dev intltool
```

Configured:
```
./autogen.sh
./configure --with-lxpanel --without-standalone --prefix=/usr --with-gnu-ld
make
sudo make install
```

This installs into `/usr/lib/lxpanel/plugins` bu I need them into `/usr/lib/x86_64-linux-gnu/lxpanel/plugins`. Made a link:
```
cd /usr/lib/x86_64-linux-gnu/lxpanel/plugins
sudo ln -s /usr/lib/lxpanel/plugins/multiload-ng.so multiload-ng.so
```
But now, cannot find `liblxpanel.so.0` after `ldd multiload-ng.so`.

**Comment by udda** [comment]
Hello! It is possible to tell *configure* which library directory to use. Please try running configure script like this:

`./configure --without-standalone --libdir=/usr/lib/x86_64-linux-gnu/`

Note that it's not necessary to add `--with-lxpanel` as it's automatically enabled if lxpanel-dev is installed.

If it works for you, we can close this issue and I will mention this situation in README. Please let me know!

**Comment by huseyinkozan** [comment]
Hi,

I cloned the master and entered these commands:
```
./autogen.sh
./configure --without-standalone --libdir=/usr/lib/x86_64-linux-gnu/
```

Lxpanel autodected:
```
....
Build Configuration:
* xfce4-panel :    no
* lxpanel     :    yes
* mate-panel  :    no
* standalone  :    no
```

Compile:
```
make
```

Some warnings:
```
  CC       multiload_ng_core_la-multiload.lo
multiload.c: In function ‘multiload_tooltip_update’:
multiload.c:57:29: warning: format not a string literal and no format arguments [-Wformat-security]
     title = g_strdup_printf(xd->cpu0_name);
                             ^
  CC       multiload_ng_core_la-multiload-colors.lo
multiload-colors.c: In function ‘multiload_colors_from_file’:
multiload-colors.c:183:15: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
  size_t len = NULL;
               ^
  CC       multiload_ng_core_la-multiload-config.lo
  CC       multiload_ng_core_la-properties.lo
  CC       multiload_ng_core_la-util.lo
util.c: In function ‘gtk_error_dialog’:
util.c:218:7: warning: format not a string literal and no format arguments [-Wformat-security]
       GTK_MESSAGE_ERROR, GTK_BUTTONS_OK, message);
       ^
util.c: In function ‘gtk_yesno_dialog’:
util.c:227:7: warning: format not a string literal and no format arguments [-Wformat-security]
       GTK_MESSAGE_QUESTION, GTK_BUTTONS_YES_NO, message);
       ^
```

Installed with `checkinstall` :
```
sudo checkinstall
```
Note: Version string was `ng-1`, fixed by setting `1.0`.

At last, `ldd` out:
```
# /usr/lib/x86_64-linux-gnu/lxpanel/plugins
$ ldd multiload-ng.so | grep not
        liblxpanel.so.0 => not found
```

**Comment by hotice** [comment]
I'm having the same issue with the lxpanel applet. It works fine with the other applets.

**Comment by udda** [comment]
Hello. I tested plugin in Lubuntu 16.04.

I am experiencing your same issue with ldd not finding *liblxpanel.so*. I will look into this, library linking is done by autotools so I have to investigate.

However, despite of this issue, Lubuntu plugin seems to work correctly. Could you confirm that?

**Comment by hotice** [comment]
I deleted my earlier comment in which I said it occurs for me too, because it actually works for me as well, even though it can't find liblxpanel.so.0.

**Comment by huseyinkozan** [comment]
I cannot see the applet. Should I reboot to activate ? Or any command to reload ?

**Comment by udda** [comment]
Restarting the panel should be enough:

`killall lxpanel; lxpanel`

Let me know if it works for you.

**Comment by udda** [comment]
Yeah I noticed these too, I think that these aren't related to plugin, as it's not using wnck.

Glad to see that the plugin is working! I'm closing this issue, feel free to open another if necessary.

**Comment by huseyinkozan** [comment]
Thanks.
