### ISSUE TITLE
Mate panel applet doesn't work with the latest Multiload-ng 1.4.0 (both GTK2 and GTK3)

### ISSUE THREAD

**Issue by hotice** [udda/multiload-ng#25]
With Multiload-ng 1.4.0, the MATE panel applet no longer works. When added to the panel, the "Multiload-ng has quit unexpectedly" popup dialog is displayed. 

The error pupup I get displays the following error: 
```
crashed with signal 5 in g_settings_get_value()
```
Tested in Ubuntu MATE 16.04 (GTK2 MATE panel and applet) and in Ubuntu MATE 16.10 (with GTK3 MATE panel and Multiload-ng applet).

Let me know if you need additional info.

**Comment by udda** [comment]
Hi Andrew! I think I located the problem. Can you try building with last commit?

**Comment by hotice** [comment]
Hey! So far I built it for GTK3 and it works properly now.

**Comment by udda** [comment]
Then it should be working good in GTK2 too (the issue was not related to GTK version).

I'll draft a minor release in minutes.
