### ISSUE TITLE
Disk graph shows nothing in Ubuntu 12.04

### ISSUE THREAD

**Issue by spvkgn** [udda/multiload-ng#28]
Shows 0 bytes regardless of selected source - auto, whole disk or sdaX partitions.

**Comment by udda** [comment]
Hello, thanks for your feedback!

Please provide me some information:
- does it show 0 even when copying a large file?
- can you provide a screenshot of filters dialog?
- which version of Multiload-ng are you using?
- in which panel are you using Multiload-ng? (Ubuntu, xfce, mate, lxde, ...)
- which system are you using? (post the output of `uname -a`)

**Comment by spvkgn** [comment]
- shows 0 when copying .iso, etc as well
- https://i.imgur.com/VScusFP.png
- latest 1.4.1 from git
- MATE, systray and standalone
- `Linux desktop 3.13.0-77-generic #121~precise1-Ubuntu SMP Wed Jan 20 18:04:08 UTC 2016 i686 i686 i386 GNU/Linux`

**Comment by udda** [comment]
Thanks for the fast reply.

This may be a recent issue. Is your Ubuntu installed in a Virtual machine?

It would be very useful to test whether it happens in older versions too. This could help me targeting the problem. Could you try in release 1.4.0 and 1.3.0?

**Comment by spvkgn** [comment]
This Ubuntu installed on real hardware. I'm afraid I can't build older version on 12.04 - https://github.com/udda/multiload-ng/issues/26

**Comment by udda** [comment]
Oh right I forgot that... OK then I have to investigate further.

**Comment by udda** [comment]
In my tests (Ubuntu 12.04 in a VM) the issue is solved now. Please let me know whether it does still happen to you :grin:
