### ISSUE TITLE
mate panel 'tooltip-style' settings reset after logout

### ISSUE THREAD

**Issue by spvkgn** [udda/multiload-ng#30]
When I set 'Tooltip style' to 'Detailed', it does reset this to 'Simple' after logout. And as far as I could see, keys `graph-*-tooltip-style` not exists in `org.mate.panel.objects.object_X.prefs`, so it seems like a bug. I can't found a way to add it manually so far.

**Comment by udda** [comment]
Your bug reports are very useful.

Actually those keys are present, but have wrong type (*boolean* instead of *integer*). Thank you for noticing that! I am already working on a fix.
