### ISSUE TITLE
mate-panel: custom colors not restored

### ISSUE THREAD

**Issue by spvkgn** [udda/multiload-ng#31]
User-defined colors not restored on logout MATE session or with `mate-panel --replace`, as follows:

Set custom background colors: ![1](https://cloud.githubusercontent.com/assets/4147135/19568641/2f109a9c-9714-11e6-9f4f-87f6d21f5d7d.png)
After logout or restart mate-panel background displays in default color: ![2](https://cloud.githubusercontent.com/assets/4147135/19568685/52dd1f0e-9714-11e6-937c-d3dda3626b56.png)

**Comment by doublemeat** [comment]
Same with xfce4-panel. Problem exists for current version of xfce4-mjultiload-ng-plugin in the ppa:nilarimogard/webupd8 repository, and prior two versions.

(It's annoying enough that I'm going to invest about 30-40 minutes finding a previous version (the one with the previous style settings dialog did preserve color settings), or just give up on this _magnificent_ and promising project for a while and check back later :-(

**Comment by udda** [comment]
No need to give up, I am already working at this for about an hour ;)

Some additional information could be useful:
- does it happen only with *background* colors or with *all* colors?
- does setting a color scheme (without editing it) work?

**Comment by doublemeat** [comment]
Awesome!

All colors are affected, even border and background. The most recent version (from ppa:nilarimogard/webupd8) does actually remember colors set from a pre-defined color theme, just not custom colors. (Whatever version I had before however did not even remember that - so, progress!)

**Comment by udda** [comment]
@doublemeat: it's not disappeared! I answered you, made some changes and marked it as *closed*.
If you missed it, click on #22 :smile:

**Comment by udda** [comment]
### Little update
I was not able to reproduce the problem in my machine.
After a few failed color changes (like you described) everything is working regularly now. Also, only MATE plugin shows this problem.

However, I am using Multiload-ng on the main development machine (where I frequently mix different versions, test new settings, and so on), so my experience may not reflect the one of final users.

So, I confirm that there is a problem, but it's so much harder to debug and fix something that I can't see. I hope you understand that.

### Little help
Could you test it again, and provide every piece of information you find relevant? In particular, please try following these steps:

1. change color(s)
2. close preferences dialog (this triggers settings save)
3. restart only the panel (via `killall mate-panel && mate-panel` and `xfce4-panel -r`) and check colors
4. change again colors(s) and close preferences dialog
5. this time logout and log back in, and check again

I need to find the situation that causes the issue. Any little difference is useful.

**Comment by spvkgn** [comment]
> change color(s)

Set custom color scheme based on 'Multiload-ng' scheme and change background color.
> close preferences dialog (this triggers settings save)
restart only the panel (via killall mate-panel && mate-panel and xfce4-panel -r) and check colors

The changed background color resets to default. In custom color scheme prefs the colors resets too. However, in gsettings `org/mate/panel/objects/object_9/prefs/` the changed colors preserves.

> change again colors(s) and close preferences dialog
this time logout and log back in, and check again

The same results here as well I see. v1.4.2

**Comment by spvkgn** [comment]
Setting color scheme without edition works. I don't fully understand what else I could check.

**Comment by udda** [comment]
Sorry, I meant other settings like size, interval, command line, tooltips, etc...
I now suppose that they do work properly.

I am coming back to this issue in a couple of hours. If I don't get to the source of the problem, I will inject some debug code.

**Comment by spvkgn** [comment]
There seems no issue with other settings as far as I can see.

**Comment by udda** [comment]
I have another little request: can you try removing Multiload-ng applet and adding a new one? Does the issue still persist?

**Comment by spvkgn** [comment]
Yes, It's still persist. Also, I tried with xfce4-panel and the same issue occurs.

**Comment by udda** [comment]
Ok Maybe I fixed it. Just tested in Arch and Ubuntu and it works well.

I need you to test lastest version in order to confirm the fix and close the issue. This version has not yet been packaged by WebUpd8, so if you want to help, you have two options:
- Build multiload-ng from source (preferred method, if you are able to)
- If you are using Ubuntu/Mint (just tell me the version) I can try to provide you a *.deb* to install with `dpkg`

**Comment by spvkgn** [comment]
I have some error when building git snapshot, please see http://pastebin.com/i9fWzZsQ

**Comment by udda** [comment]
Seems easily solvable. Could you please post your `config.log`?

**Comment by spvkgn** [comment]
With latest git some another error appears: http://pastebin.com/5YYJFep7
config.log http://pastebin.com/uGcMDinr

**Comment by udda** [comment]
I'm sorry, this kind of things just happens with development code...

I fixed this one too, please try again with lastest code

**Comment by spvkgn** [comment]
I tested it and it seems it works like a charm now. Thank you so much!

**Comment by udda** [comment]
Very happy to know that :smile:

**Comment by doublemeat** [comment]
I'm on Xubuntu 16.04. I just got a new laptop so dev environment not set up yet - if you happen to have a .deb laying around, I'll install and test it!

**Comment by udda** [comment]
I'm rather new to Debian packaging, but I'm trying to make a deb for you in a few hours :sunglasses:

Anyway, the problem seems to be solved (albeit I'm waiting for your confirmation too), but this will give you a taste of the newer features!

**Comment by udda** [comment]
Here are two *deb* files I created with [Multiload-ng builtin package generator](https://github.com/udda/multiload-ng/tree/master/extras). I have no means of testing them, but other people previously reported that packages generated this way do work well.

- the first was created within Ubuntu 16.04 (32 bit)
- the second was created within Gentoo (64 bit), but should be installable in 64 bit *Ubuntu without any problem

Choose the one that suits your architecture. I hope these work! I can't test them since I am not using Ubuntu.

[multiload-ng_1.4.2.20161030-1_i386.deb](https://github.com/udda/multiload-ng/files/560575/i386.zip)
[multiload-ng_1.4.2.20161030-1_amd64.deb](https://github.com/udda/multiload-ng/files/560574/amd64.zip)

Note: **these packages are not redistributable!** These were created to test a **development** version, these are simply not ready for release, just for testing purposes.
Before installing, you might need to uninstall any other release package of Multiload-ng (including WebUpd8 ones), and then when you are reinstalling WebUpd8 official packages, remove the one you installed from here. (preferences are not removed with the package)

**Comment by doublemeat** [comment]
FYI - I couldn't get your multiload-ng_1.4.2.20161030-1_amd64.deb above to install.

Xubuntu 16.04.1, x86_64, kernel 4.4.0-47-generic.

The Ubuntu "Software" manager, upon trying to open it, would give the error: "Sorry, this did not work", "no file_to_app results to show".

It loaded without complaint in gdebi (graphical deb installer), and when you click "Install", it seems to - but doesn't. (And normally the "Install" button goes away upon success, replaced by "Reinstall" and "Uninstall", but doesn't.) If you click on the Lintian output tab, you see this:

> dpkg-deb: error: file '/home/user/Downloads/multiload-ng_1.4.2.20161030-1_amd64.deb' is not a debian binary archive (try dpkg-split?)
> /bin/tar: This does not look like a tar archive
> /bin/tar: *control: Not found in archive
> /bin/tar: Exiting with failure status due to previous errors
> Skipping /home/user/Downloads/multiload-ng_1.4.2.20161030-1_amd64.deb: could not read control data in /home/user/Downloads/multiload-ng_1.4.2.20161030-1_amd64.deb:  at /usr/share/perl5/Lintian/ProcessablePool.pm line 91.
> 
> Lintian finished with exit status 2

So I rebuilt the deb. Steps:
- Extracted the "usr" folder from the deb archive.
- Changed owner:group to root
- Made sure stuff was marked executable (e.g. the .desktop files weren't).
- Copied "usr/share/locale/es" to "en", just in case that was causing any problems.
- Rebuilt using dpkg-deb, following the basic steps here: [https://ubuntuforums.org/showthread.php?t=910717&s=ff9d4a3b6daf2999e2dcd53285aba3d2&p=5728953#post5728953](https://ubuntuforums.org/showthread.php?t=910717&s=ff9d4a3b6daf2999e2dcd53285aba3d2&p=5728953#post5728953)

The gdebi Lintian output wasn't flawless, but seemed like minor problems, and it seems to have installed fine. I'm not sure I can upload a file here, but I'd be happy to email it to you.

**Comment by udda** [comment]
That .deb file was simply badly generated :hurtrealbad: I told you that I am not good with Debian packaging...

You can just ignore that file, there is a new release and I'm sure that Andrew @ WebUpd8 is already at work to add to its PPA.

The important thing is that it solved the issue for you! :feelsgood:

**Comment by doublemeat** [comment]
Well done on the Doom Guy! ;-)
