### ISSUE TITLE
ram size

### ISSUE THREAD

**Issue by makrochip** [udda/multiload-ng#35]
very nice applet, thank you 
version 1.4 on xubuntu 16.04
just a small issue, total ram size mismatch, however usage percentage is ok, so graph shows fine
have 24G installed and applet shows only 3.5G

![multiload-ng](https://cloud.githubusercontent.com/assets/5619782/19790634/f7e88f2e-9cb9-11e6-821f-d6dadca10ea6.png)

**Comment by udda** [comment]
Hello, thank you for the feedback!

Well, there are good news. The issue you are describing was already solved in development code (specifically by [commit b7e6faf](https://github.com/udda/multiload-ng/commit/b7e6faf6307c4656a55b0855e7aa129e00a4754a)). You just need to wait the next release :sunglasses:
