### ISSUE TITLE
Custom color scheme resets itself on reboot (xfce-panel)

### ISSUE THREAD

**Issue by Moondownr** [udda/multiload-ng#38]
I can export my custom color scheme to a file and then import it, but I have to do it on each boot - it auto resets to a default color scheme. I feel like I must be missing something obvious (sorry if I am), but I see no way to make multiload-ng start with my color scheme.

**Comment by udda** [comment]
Hello, thanks for your feedback!

I need some additional information:
- what version of Multiload-ng are you using?
- are you building from source? How did you get Multiload-ng installed in your system?
- which distro? (Ubuntu, Arch, Mint...)

Similar issues (like #31) has already been solved in development code, meaning that next release (coming soon) doesn't suffer of this problem. If you are using v1.4.2 (from WebUpd8 PPA, for example), this may be the case.

**Comment by Moondownr** [comment]
Hello,
I'm using the version from WebUpd8 PPA on Xubuntu 16.04 (however it's 1.4.0-1, not 1.4.2). Installed following this [guide](http://www.webupd8.org/2016/08/alternative-system-monitor-applet-for.html) Glad to hear it's already fixed in development code :)

**Comment by udda** [comment]
I will release v1.5.0 soon - the problem you are describing is definitely solved! Therefore I am closing this issue.

Thanks for taking the time to file a bug! :smile:
