### ISSUE TITLE
Missing translation in mate-panel right-click menu entries

### ISSUE THREAD

**Issue by spvkgn** [udda/multiload-ng#39]
`About` and `Preferences` entries are not translated. I would add translation manually in ru.po file but did not found this entries there. 

![1](https://cloud.githubusercontent.com/assets/4147135/20239606/5776582e-a92e-11e6-8592-4a8bd529de50.png)

**Comment by udda** [comment]
Thanks, I didn't notice that! Those strings aren't translated in any language.

These default (Stock) menu entries used to be translated automatically by GTK - same goes for e.g. *Close*, *Save*, etc.
With GTK+3, stock items were deprecated, and automatic translation is no more available. I will copy localized strings from GTK source.
