### ISSUE TITLE
Fails to find LXPANEL in Ubuntu 14.04

### ISSUE THREAD

**Issue by hotice** [udda/multiload-ng#42]
I'm trying to build multiload-ng in Ubuntu 14.04 (with GTK2) for my PPA, but it fails to find LXPANEL. Here's the build log: https://launchpadlibrarian.net/293501645/buildlog_ubuntu-trusty-amd64.multiload-ng_1.5.0-1~webupd8~trusty1_BUILDING.txt.gz

Ubuntu 14.04 (Trusty Tahr) has lxpanel 0.6.1, as you can see here: https://launchpad.net/ubuntu/+source/lxpanel

Any idea why this is happening? Maybe it's something related to Ubuntu 14.04 and not multiload-ng?

On a side note, Ubuntu didn't have a -dev package for lxpanel until Ubuntu 16.04, however, I've built packages for Ubuntu 15.04 and 15.10 just fine by using just 'lxpanel' as the build dependency.

**Comment by udda** [comment]
LxPanel has radically changed its internal API starting from 0.7.0, and begun adding *include* files and *pkg-config* files straight into main package (these are usually the contents of -dev package).

I can see that in [Trusty lxpanel deb](https://launchpad.net/ubuntu/+archive/primary/+files/lxpanel_0.6.1-0ubuntu3_amd64.deb) these files are missing. The strange thing is that they are present in Precise, Utopic and later, only Trusty packages misses those files. Even more strange, [Launchpad source for Trusty lxpanel](https://launchpad.net/ubuntu/+archive/primary/+files/lxpanel_0.6.1.orig.tar.gz) actually builds and installs these files, but for some reason they aren't present in the final deb.

I can confirm that building with lxpanel 0.6.1 works in Arch and Gentoo.

**Comment by hotice** [comment]
Nothing you or I can do about it then... I'll close this bug.

**Comment by udda** [comment]
A "manual" workaround could be copying from source the files: `/usr/include/lxpanel/plugin.h` and `/usr/lib/pkgconfig/lxpanel.pc`, and install them in development machine. This should work (although I can't be sure until we try), also these files are required only for building so there is nothing to do on PPA or debs.

This is somewhat a hack, but I can provide these files if you want to try.

**Comment by hotice** [comment]
There's no way to do that with the PPA package. I just upload a package and Launchpad does the rest. Anyway, at least the indicator works in Lubuntu 14.04.

**Comment by udda** [comment]
Sorry, I didn't know, I have no experience with Launchpad and PPAs. Well, then we have absolutely no options.
