### ISSUE TITLE
Apply button

### ISSUE THREAD

**Issue by leoheck** [udda/multiload-ng#43]
Needs an ``apply`` button to change it without closing the window. There are many customization options, but closing and opening is boring during customization process.

**Comment by udda** [comment]
Hello, thanks for your feedback!

What version of Multiload-ng are you using?

You may be happy to know that (at least in newer versions) the settings are applied in the moment that you change them, there is no need to close the window.
Doesn't it work this way for you?

**Comment by leoheck** [comment]
Hi, I am using the last ppa's version on ubuntu. Now I don't know which version is, I will see it once I get home. Thank you.

**Comment by udda** [comment]
Then you should have 1.4.0 or 1.5.0 (if you upgraded today). Waiting for your response :smile:

**Comment by leoheck** [comment]
I have version 1.5, and it is working now. :+1:

**Comment by udda** [comment]
Great to know! Then I'm closing this issue :smile:
