### ISSUE TITLE
Graphs size

### ISSUE THREAD

**Issue by leoheck** [udda/multiload-ng#45]
Graphs size are wrong for me. For example, using 100 px it shows almos 55 px.

**Comment by udda** [comment]
Please give me more details.
- What's your Ubuntu version?
- Can you provide a screenshot of preferences dialog and graphs together?

**Comment by leoheck** [comment]
Sure! I am using Ubuntu 16.04, look: (indicator with black background is multiload-ng)

![g8749](https://cloud.githubusercontent.com/assets/1277920/20369734/e065af5c-ac41-11e6-8979-5d839ebe5af8.png)

Changing, one box to 200 px for example, reduces the size of all other boxes, look:
The 200 px box hides other boxes.

![screenshot from 2016-11-16 21-17-30](https://cloud.githubusercontent.com/assets/1277920/20369779/2887a254-ac42-11e6-849f-10a8cfb0677c.png)

**Comment by udda** [comment]
This happens only with GTK+2 builds of Indicator (like the one in PPA). I think I found out why it happens and I am already at work to fix that!

**Comment by udda** [comment]
Just tested in Ubuntu 16.04 and the issue is solved. I will publish a minor release soon with the fix.

Thank you very much for reporting!
