### ISSUE TITLE
Makefile uses absolute paths

### ISSUE THREAD

**Issue by Photon89** [udda/multiload-ng#8]
When building a package using makepkg (Arch Linux), things are installed in a fakeroot environment. That is, if I have a PKGBUILD file (which carries the building instructions) in some folder somefolder/PKGBUILD, the source is downloaded to $srcdir=somefolder/src and installed into $pkgdir=somefolder/pkg. The package then includes the contents of $pkgdir which are copied to / by the package manager.

Now, if I use the prefix /usr in the PKGBUILD, make install tries to write to /usr rather than $pkgdir/usr and fails due to permission errors. If I use the prefix $pkgdir/usr, the absolute path "somedir/pkg/usr" is being used in many binary files (i can supply a list if needed). Please edit the makefile such that the absolute path of the prefix is not being used.

edit: Note: It worked before the latest update (though there was a warning, about the absolute path being found somewhere, I couldn't find it anywhere and things actually worked fine).

**Comment by udda** [comment]
Please try building now.
I removed external dependencies completely, now Glade files are embedded into main executable, so no more path problems.

If this does not solve the issue, that list of absolute path references could be useful.

**Comment by Photon89** [comment]
Seems to have solved the problem, thanks for the fast fix!
