### ISSUE TITLE
lxpanel applet does not remember configuration

### ISSUE THREAD

**Issue by huseyinkozan** [udda/multiload-ng#9]
Hello,
I am changing the colors, but lxpanel applet does not remember configuration. 
Should I use Export and/or Import functions to write *.colors file any known place like ~/.conf/ ?

**Comment by udda** [comment]
Hello, thanks for the report.

No, exported color schemes are meant to be kept as a backup, or as a part of a downloadable collection. Settings should be saved automatically.

I am experiencing this issue too. From a quick Google search appears that this is a known bug of lxpanel, that affects also other plugins from time to time.

I will try to force a config write. Let me know whether it works.

**Comment by huseyinkozan** [comment]
Thanks for the interest. I will be happy to test it : ^ )

Note : I want to change only network outgoing color to a green value. It is more informal than a darker one. You may thing about it ; ^ )

**Comment by udda** [comment]
For cleanliness purposes, in the default theme every graph has its own distinctive color and uses only shades of that color (including for border and background).
Mixing colors between graphs might make them difficult to distinguish at first glance. In my opinion this could generate confusion among the users.

So I'm not going to change default color scheme that much, but I'm open to suggestion about minor modifications that follow the directive above.

Nevertheless, if you create a great color scheme, you can submit it to me and we'll work on it!

**Comment by huseyinkozan** [comment]
I am not pro about visual design. And not want to effect other people. Just want to give a suggestion.

Thanks anyway.

**Comment by udda** [comment]
Your opinion is valuable to me. I'm sorry if I made you believe otherwise.

Feedback from users it is ALWAYS a good thing. Feel free to give other thoughts if you like.

Have a nice day! :)
